# Generated by Django 3.0.4 on 2020-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('Year_int', models.IntegerField(default=0)),
                ('Year_char', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('sub_chapter', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('pdf', models.FileField(upload_to='pdfs')),
            ],
        ),
    ]
